---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates
      apt:
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - name: docker_Ubuntu

